# title: "Tellusant Publications"
# description: "Published materials by Tellusant team members"

url: "https://tellusant.github.io"   # no trailing slash
baseurl: "/docs"                      # project path

